### ISSUE TITLE
Air Map 장고 환경 설정

### ISSUE THREAD

**Issue by lioliolio** [FCSProjectAirMap/AirMap_WPS#1]
- `requirements.txt` 만들기
- `settings` 분리

**Comment by lioliolio** [comment]
개발용, 배포용 패키지 분리
settings 모듈 분리
django project SECRET_KEY .env에 이동
pep8, travis setting

**Comment by wonju** [comment]
나도 develop branch에서 pull 완료.. 이제 본격적인 개발 시작~~

**Comment by junoooya** [comment]
수고하셨습니다.!!
