### ISSUE TITLE
User Model 생성하기

### ISSUE THREAD

**Issue by lioliolio** [FCSProjectAirMap/AirMap_WPS#2]
- 확장성을 고려하여 User Model 생성
- `username`, `password`, `가입일시` `username` 는 email 주소

**Comment by wonju** [comment]
확장성 고려한 모델 생성하였습니다.
앞으로 필요한 데이터에 따라 확장할 가능성 있지만 이번 이슈는 완료 되었으니 닫아주세요^^

**Comment by lioliolio** [comment]
수고하셨습니다.
